services:
  backend:
    build: ./backend
    env_file:
      - .env 
    ports:
      - 4000:4000
  db:
    image: mysql
    restart: always  
    command: mysqld --init-file="/data/application/init.sql"
    volumes: 
      - ./database/init.sql:/data/application/init.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1      
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
volumes:
  index_data:
    driver: local
  backups:
    driver: local