DROP DATABASE IF EXISTS ayoub_db;
CREATE DATABASE ayoub_db;

USE ayoub_db;
CREATE TABLE APP_USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);